// Fictional publication fixtures only. No real student or staff records.
import type { MockAuditEvent } from './types'

export const auditEvents: MockAuditEvent[] = [
  // ---------------- synthetic-cases-001 ----------------
  {
    id: 'synthetic-audit-001',
    caseId: 'synthetic-cases-001',
    actorName: 'System',
    actorRole: 'system',
    action: 'Case created from ISIR ingest',
    timestamp: '2026-03-09T12:00:00Z',
    details: 'Synthetic audit detail for demonstration.',
  },
  {
    id: 'synthetic-audit-002',
    caseId: 'synthetic-cases-001',
    actorName: 'System',
    actorRole: 'system',
    action: 'Rules engine generated 4 V1 tasks',
    timestamp: '2026-03-09T12:00:00Z',
  },
  {
    id: 'synthetic-audit-003',
    caseId: 'synthetic-cases-001',
    actorName: 'System',
    actorRole: 'system',
    action: 'Notification sent to student (Spanish)',
    timestamp: '2026-03-09T12:00:00Z',
  },
  {
    id: 'synthetic-audit-004',
    caseId: 'synthetic-cases-001',
    actorName: 'Student One',
    actorRole: 'student',
    action: 'Started family size worksheet',
    timestamp: '2026-03-09T12:00:00Z',
  },

  // ---------------- synthetic-cases-002 ----------------
  {
    id: 'synthetic-audit-005',
    caseId: 'synthetic-cases-002',
    actorName: 'System',
    actorRole: 'system',
    action: 'Case created from ISIR ingest',
    timestamp: '2026-03-10T12:00:00Z',
  },
  {
    id: 'synthetic-audit-006',
    caseId: 'synthetic-cases-002',
    actorName: 'System',
    actorRole: 'system',
    action: 'Rules engine generated 4 V1 tasks',
    timestamp: '2026-03-10T12:00:00Z',
  },
  {
    id: 'synthetic-audit-007',
    caseId: 'synthetic-cases-002',
    actorName: 'Student Four',
    actorRole: 'student',
    action: 'Started tax return upload',
    timestamp: '2026-03-10T12:00:00Z',
  },

  // ---------------- synthetic-cases-003 ----------------
  {
    id: 'synthetic-audit-008',
    caseId: 'synthetic-cases-003',
    actorName: 'System',
    actorRole: 'system',
    action: 'Case created from ISIR ingest',
    timestamp: '2026-03-11T12:00:00Z',
  },
  {
    id: 'synthetic-audit-009',
    caseId: 'synthetic-cases-003',
    actorName: 'System',
    actorRole: 'system',
    action: 'Assigned to Staff Three',
    timestamp: '2026-03-11T12:00:00Z',
  },
  {
    id: 'synthetic-audit-010',
    caseId: 'synthetic-cases-003',
    actorName: 'Student Six',
    actorRole: 'student',
    action: "Student uploaded family size worksheet",
    timestamp: '2026-03-11T12:00:00Z',
  },
  {
    id: 'synthetic-audit-011',
    caseId: 'synthetic-cases-003',
    actorName: 'Staff Three',
    actorRole: 'reviewer',
    action: "Task 'Verify family size' approved",
    timestamp: '2026-03-11T12:00:00Z',
  },
  {
    id: 'synthetic-audit-012',
    caseId: 'synthetic-cases-003',
    actorName: 'Student Six',
    actorRole: 'student',
    action: 'Student uploaded tax return transcript',
    timestamp: '2026-03-11T12:00:00Z',
  },
  {
    id: 'synthetic-audit-013',
    caseId: 'synthetic-cases-003',
    actorName: 'Student Six',
    actorRole: 'student',
    action: 'Student uploaded W-2',
    timestamp: '2026-03-11T12:00:00Z',
  },
  {
    id: 'synthetic-audit-014',
    caseId: 'synthetic-cases-003',
    actorName: 'Staff Three',
    actorRole: 'reviewer',
    action: 'Case moved to in_review',
    timestamp: '2026-03-11T12:00:00Z',
  },

  // ---------------- synthetic-cases-004 ----------------
  {
    id: 'synthetic-audit-015',
    caseId: 'synthetic-cases-004',
    actorName: 'System',
    actorRole: 'system',
    action: 'Case created from ISIR ingest',
    timestamp: '2026-03-12T12:00:00Z',
    details: 'Synthetic audit detail for demonstration.',
  },
  {
    id: 'synthetic-audit-016',
    caseId: 'synthetic-cases-004',
    actorName: 'System',
    actorRole: 'system',
    action: 'Assigned to Staff One',
    timestamp: '2026-03-12T12:00:00Z',
  },
  {
    id: 'synthetic-audit-017',
    caseId: 'synthetic-cases-004',
    actorName: 'Student Two',
    actorRole: 'student',
    action: 'Student uploaded family size worksheet',
    timestamp: '2026-03-12T12:00:00Z',
  },
  {
    id: 'synthetic-audit-018',
    caseId: 'synthetic-cases-004',
    actorName: 'Staff One',
    actorRole: 'counselor',
    action: "Task 'Verify family size' approved",
    timestamp: '2026-03-12T12:00:00Z',
  },
  {
    id: 'synthetic-audit-019',
    caseId: 'synthetic-cases-004',
    actorName: 'Staff One',
    actorRole: 'counselor',
    action: 'Verification complete — case approved',
    timestamp: '2026-03-12T12:00:00Z',
  },

  // ---------------- synthetic-cases-005 ----------------
  {
    id: 'synthetic-audit-020',
    caseId: 'synthetic-cases-005',
    actorName: 'System',
    actorRole: 'system',
    action: 'Case created from ISIR ingest',
    timestamp: '2026-03-13T12:00:00Z',
  },
  {
    id: 'synthetic-audit-021',
    caseId: 'synthetic-cases-005',
    actorName: 'System',
    actorRole: 'system',
    action: 'Assigned to Staff Two',
    timestamp: '2026-03-13T12:00:00Z',
  },
  {
    id: 'synthetic-audit-022',
    caseId: 'synthetic-cases-005',
    actorName: 'Student Seven',
    actorRole: 'student',
    action: 'Student uploaded tax return transcript',
    timestamp: '2026-03-13T12:00:00Z',
  },
  {
    id: 'synthetic-audit-023',
    caseId: 'synthetic-cases-005',
    actorName: 'Staff Two',
    actorRole: 'counselor',
    action: "Task 'Upload tax return' rejected",
    timestamp: '2026-03-13T12:00:00Z',
    details: 'Synthetic audit detail for demonstration.',
  },
  {
    id: 'synthetic-audit-024',
    caseId: 'synthetic-cases-005',
    actorName: 'Staff Two',
    actorRole: 'counselor',
    action: 'Correction submitted to FAFSA Partner Portal',
    timestamp: '2026-03-13T12:00:00Z',
  },

  // ---------------- synthetic-cases-006 ----------------
  {
    id: 'synthetic-audit-025',
    caseId: 'synthetic-cases-006',
    actorName: 'System',
    actorRole: 'system',
    action: 'Case created from ISIR ingest',
    timestamp: '2026-03-14T12:00:00Z',
  },
  {
    id: 'synthetic-audit-026',
    caseId: 'synthetic-cases-006',
    actorName: 'System',
    actorRole: 'system',
    action: 'Assigned to Staff Four',
    timestamp: '2026-03-14T12:00:00Z',
  },
  {
    id: 'synthetic-audit-027',
    caseId: 'synthetic-cases-006',
    actorName: 'Student Twelve',
    actorRole: 'student',
    action: 'Student uploaded documents',
    timestamp: '2026-03-14T12:00:00Z',
  },
  {
    id: 'synthetic-audit-028',
    caseId: 'synthetic-cases-006',
    actorName: 'Staff Four',
    actorRole: 'reviewer',
    action: 'Requested resubmission (illegible transcript)',
    timestamp: '2026-03-14T12:00:00Z',
  },
  {
    id: 'synthetic-audit-029',
    caseId: 'synthetic-cases-006',
    actorName: 'Staff Four',
    actorRole: 'reviewer',
    action: 'Case rejected after three resubmission attempts',
    timestamp: '2026-03-14T12:00:00Z',
    details: 'Synthetic audit detail for demonstration.',
  },

  // ---------------- synthetic-cases-007 ----------------
  {
    id: 'synthetic-audit-030',
    caseId: 'synthetic-cases-007',
    actorName: 'System',
    actorRole: 'system',
    action: 'Case created from ISIR ingest',
    timestamp: '2026-03-15T12:00:00Z',
    details: 'Synthetic audit detail for demonstration.',
  },
  {
    id: 'synthetic-audit-031',
    caseId: 'synthetic-cases-007',
    actorName: 'System',
    actorRole: 'system',
    action: 'Assigned to Staff Three',
    timestamp: '2026-03-15T12:00:00Z',
  },
  {
    id: 'synthetic-audit-032',
    caseId: 'synthetic-cases-007',
    actorName: 'Student Eleven',
    actorRole: 'student',
    action: 'Student uploaded family size worksheet',
    timestamp: '2026-03-15T12:00:00Z',
  },
  {
    id: 'synthetic-audit-033',
    caseId: 'synthetic-cases-007',
    actorName: 'Staff Three',
    actorRole: 'reviewer',
    action: 'Verification complete — case approved',
    timestamp: '2026-03-15T12:00:00Z',
  },

  // ---------------- synthetic-cases-008 ----------------
  {
    id: 'synthetic-audit-034',
    caseId: 'synthetic-cases-008',
    actorName: 'System',
    actorRole: 'system',
    action: 'Case created from ISIR ingest',
    timestamp: '2026-03-16T12:00:00Z',
    details: 'Synthetic audit detail for demonstration.',
  },
  {
    id: 'synthetic-audit-035',
    caseId: 'synthetic-cases-008',
    actorName: 'System',
    actorRole: 'system',
    action: 'Student selected in-person identity method',
    timestamp: '2026-03-16T12:00:00Z',
  },
  {
    id: 'synthetic-audit-036',
    caseId: 'synthetic-cases-008',
    actorName: 'System',
    actorRole: 'system',
    action: 'Reminder notification sent',
    timestamp: '2026-03-16T12:00:00Z',
  },

  // ---------------- synthetic-cases-009 ----------------
  {
    id: 'synthetic-audit-037',
    caseId: 'synthetic-cases-009',
    actorName: 'System',
    actorRole: 'system',
    action: 'Case created from ISIR ingest',
    timestamp: '2026-03-17T12:00:00Z',
  },
  {
    id: 'synthetic-audit-038',
    caseId: 'synthetic-cases-009',
    actorName: 'System',
    actorRole: 'system',
    action: 'Assigned to Staff Three',
    timestamp: '2026-03-17T12:00:00Z',
  },
  {
    id: 'synthetic-audit-039',
    caseId: 'synthetic-cases-009',
    actorName: 'Student Eight',
    actorRole: 'student',
    action: 'Scheduled identity video call',
    timestamp: '2026-03-17T12:00:00Z',
  },
  {
    id: 'synthetic-audit-040',
    caseId: 'synthetic-cases-009',
    actorName: 'Staff Three',
    actorRole: 'reviewer',
    action: 'Identity video call completed',
    timestamp: '2026-03-17T12:00:00Z',
    details: 'Synthetic audit detail for demonstration.',
  },

  // ---------------- synthetic-cases-010 ----------------
  {
    id: 'synthetic-audit-041',
    caseId: 'synthetic-cases-010',
    actorName: 'System',
    actorRole: 'system',
    action: 'Case created from ISIR ingest',
    timestamp: '2026-03-18T12:00:00Z',
  },
  {
    id: 'synthetic-audit-042',
    caseId: 'synthetic-cases-010',
    actorName: 'System',
    actorRole: 'system',
    action: 'Assigned to Staff Four',
    timestamp: '2026-03-18T12:00:00Z',
  },
  {
    id: 'synthetic-audit-043',
    caseId: 'synthetic-cases-010',
    actorName: 'Student Five',
    actorRole: 'student',
    action: 'Completed Persona IAL2 verification',
    timestamp: '2026-03-18T12:00:00Z',
  },
  {
    id: 'synthetic-audit-044',
    caseId: 'synthetic-cases-010',
    actorName: 'Staff Four',
    actorRole: 'reviewer',
    action: 'Verification complete — case approved',
    timestamp: '2026-03-18T12:00:00Z',
    details: 'Synthetic audit detail for demonstration.',
  },

  // ---------------- synthetic-cases-011 ----------------
  {
    id: 'synthetic-audit-045',
    caseId: 'synthetic-cases-011',
    actorName: 'System',
    actorRole: 'system',
    action: 'Case created from ISIR ingest',
    timestamp: '2026-03-19T12:00:00Z',
    details: 'Synthetic audit detail for demonstration.',
  },
  {
    id: 'synthetic-audit-046',
    caseId: 'synthetic-cases-011',
    actorName: 'System',
    actorRole: 'system',
    action: 'Rules engine generated 3 tasks (family size + identity)',
    timestamp: '2026-03-19T12:00:00Z',
  },
  {
    id: 'synthetic-audit-047',
    caseId: 'synthetic-cases-011',
    actorName: 'System',
    actorRole: 'system',
    action: 'Persona IAL2 link delivered via SMS',
    timestamp: '2026-03-19T12:00:00Z',
  },
  {
    id: 'synthetic-audit-048',
    caseId: 'synthetic-cases-011',
    actorName: 'Student Nine',
    actorRole: 'student',
    action: 'Started family size worksheet',
    timestamp: '2026-03-19T12:00:00Z',
  },

  // ---------------- synthetic-cases-012 ----------------
  {
    id: 'synthetic-audit-049',
    caseId: 'synthetic-cases-012',
    actorName: 'System',
    actorRole: 'system',
    action: 'Case created from ISIR ingest',
    timestamp: '2026-03-20T12:00:00Z',
  },
  {
    id: 'synthetic-audit-050',
    caseId: 'synthetic-cases-012',
    actorName: 'System',
    actorRole: 'system',
    action: 'Assigned to Staff One',
    timestamp: '2026-03-20T12:00:00Z',
  },
  {
    id: 'synthetic-audit-051',
    caseId: 'synthetic-cases-012',
    actorName: 'Student One',
    actorRole: 'student',
    action: 'Student uploaded family size worksheet',
    timestamp: '2026-03-20T12:00:00Z',
  },
  {
    id: 'synthetic-audit-052',
    caseId: 'synthetic-cases-012',
    actorName: 'Staff One',
    actorRole: 'counselor',
    action: "Task 'Verify family size' approved",
    timestamp: '2026-03-20T12:00:00Z',
  },
  {
    id: 'synthetic-audit-053',
    caseId: 'synthetic-cases-012',
    actorName: 'Student One',
    actorRole: 'student',
    action: 'Uploaded tax return and W-2 documents',
    timestamp: '2026-03-20T12:00:00Z',
  },
  {
    id: 'synthetic-audit-054',
    caseId: 'synthetic-cases-012',
    actorName: 'Student One',
    actorRole: 'student',
    action: 'Completed identity video call',
    timestamp: '2026-03-20T12:00:00Z',
  },

  // ---------------- synthetic-cases-013 ----------------
  {
    id: 'synthetic-audit-055',
    caseId: 'synthetic-cases-013',
    actorName: 'System',
    actorRole: 'system',
    action: 'Case created from ISIR ingest',
    timestamp: '2026-03-21T12:00:00Z',
  },
  {
    id: 'synthetic-audit-056',
    caseId: 'synthetic-cases-013',
    actorName: 'System',
    actorRole: 'system',
    action: 'Assigned to Staff Two',
    timestamp: '2026-03-21T12:00:00Z',
  },
  {
    id: 'synthetic-audit-057',
    caseId: 'synthetic-cases-013',
    actorName: 'Student Six',
    actorRole: 'student',
    action: 'Completed in-person identity verification',
    timestamp: '2026-03-21T12:00:00Z',
  },
  {
    id: 'synthetic-audit-058',
    caseId: 'synthetic-cases-013',
    actorName: 'Staff Two',
    actorRole: 'counselor',
    action: "Task 'Verify identity' approved",
    timestamp: '2026-03-21T12:00:00Z',
  },
  {
    id: 'synthetic-audit-059',
    caseId: 'synthetic-cases-013',
    actorName: 'Staff Two',
    actorRole: 'counselor',
    action: "Task 'Upload W-2' rejected — wage mismatch",
    timestamp: '2026-03-21T12:00:00Z',
    details: 'Synthetic audit detail for demonstration.',
  },
  {
    id: 'synthetic-audit-060',
    caseId: 'synthetic-cases-013',
    actorName: 'Staff Two',
    actorRole: 'counselor',
    action: 'Correction submitted to FAFSA Partner Portal',
    timestamp: '2026-03-21T12:00:00Z',
  },

  // ---------------- synthetic-cases-014 ----------------
  {
    id: 'synthetic-audit-061',
    caseId: 'synthetic-cases-014',
    actorName: 'System',
    actorRole: 'system',
    action: 'Case created from ISIR ingest',
    timestamp: '2026-03-22T12:00:00Z',
  },
  {
    id: 'synthetic-audit-062',
    caseId: 'synthetic-cases-014',
    actorName: 'System',
    actorRole: 'system',
    action: 'Assigned to Staff Four',
    timestamp: '2026-03-22T12:00:00Z',
  },
  {
    id: 'synthetic-audit-063',
    caseId: 'synthetic-cases-014',
    actorName: 'Student Twelve',
    actorRole: 'student',
    action: 'Uploaded tax return transcript',
    timestamp: '2026-03-22T12:00:00Z',
  },
  {
    id: 'synthetic-audit-064',
    caseId: 'synthetic-cases-014',
    actorName: 'Staff Four',
    actorRole: 'reviewer',
    action: 'Flagged transcript for possible fraud',
    timestamp: '2026-03-22T12:00:00Z',
    details: 'Synthetic audit detail for demonstration.',
  },
  {
    id: 'synthetic-audit-065',
    caseId: 'synthetic-cases-014',
    actorName: 'Staff Four',
    actorRole: 'reviewer',
    action: 'Case escalated to director for review',
    timestamp: '2026-03-22T12:00:00Z',
  },
  {
    id: 'synthetic-audit-066',
    caseId: 'synthetic-cases-014',
    actorName: 'Staff Five',
    actorRole: 'director',
    action: 'Director acknowledged escalation',
    timestamp: '2026-03-22T12:00:00Z',
  },
  {
    id: 'synthetic-audit-067',
    caseId: 'synthetic-cases-014',
    actorName: 'Staff Five',
    actorRole: 'director',
    action: 'Persona returned NEEDS_REVIEW — additional verification required',
    timestamp: '2026-03-22T12:00:00Z',
  },
]
