// Fictional publication fixtures only. No real student or staff records.
import type { MockStudent } from './types'

export const students: MockStudent[] = [
  {
    id: 'synthetic-student-001',
    bannerId: 'SYN000001',
    firstName: 'Student',
    lastName: 'One',
    preferredName: 'Student',
    ssnLast4: '0000',
    ssnMasked: '***-**-0000',
    dob: '2000-01-01',
    email: 'student.one@example.com',
    phoneMasked: '(***) ***-0100',
    enrollmentStatus: 'enrolled',
    program: 'Example Program',
    preferredLanguage: 'es',
    faDdxPopulated: false,
    awards: [
      { kind: 'pell', amount: 1000, status: 'estimated' },
      { kind: 'tops', amount: 1000, status: 'estimated' },
    ],
  },
  {
    id: 'synthetic-student-002',
    bannerId: 'SYN000002',
    firstName: 'Student',
    lastName: 'Two',
    ssnLast4: '0000',
    ssnMasked: '***-**-0000',
    dob: '2000-01-01',
    email: 'student.two@example.com',
    phoneMasked: '(***) ***-0100',
    enrollmentStatus: 'enrolled',
    program: 'Example Program',
    preferredLanguage: 'en',
    faDdxPopulated: true,
    awards: [
      { kind: 'pell', amount: 1000, status: 'awarded' },
      { kind: 'go_grant', amount: 1000, status: 'awarded' },
    ],
  },
  {
    id: 'synthetic-student-003',
    bannerId: 'SYN000003',
    firstName: 'Student',
    lastName: 'Three',
    preferredName: 'Student',
    ssnLast4: '0000',
    ssnMasked: '***-**-0000',
    dob: '2000-01-01',
    email: 'student.three@example.com',
    phoneMasked: '(***) ***-0100',
    enrollmentStatus: 'enrolled',
    program: 'Example Program',
    preferredLanguage: 'vi',
    faDdxPopulated: true,
    awards: [
      { kind: 'pell', amount: 1000, status: 'disbursed' },
      { kind: 'tops', amount: 1000, status: 'disbursed' },
    ],
  },
  {
    id: 'synthetic-student-004',
    bannerId: 'SYN000004',
    firstName: 'Student',
    lastName: 'Four',
    ssnLast4: '0000',
    ssnMasked: '***-**-0000',
    dob: '2000-01-01',
    email: 'student.four@example.com',
    phoneMasked: '(***) ***-0100',
    enrollmentStatus: 'enrolled',
    program: 'Example Program',
    preferredLanguage: 'en',
    faDdxPopulated: false,
    awards: [{ kind: 'pell', amount: 1000, status: 'estimated' }],
  },
  {
    id: 'synthetic-student-005',
    bannerId: 'SYN000005',
    firstName: 'Student',
    lastName: 'Five',
    ssnLast4: '0000',
    ssnMasked: '***-**-0000',
    dob: '2000-01-01',
    email: 'student.five@example.com',
    phoneMasked: '(***) ***-0100',
    enrollmentStatus: 'enrolled',
    program: 'Example Program',
    preferredLanguage: 'en',
    faDdxPopulated: true,
    awards: [
      { kind: 'pell', amount: 1000, status: 'awarded' },
      { kind: 'go_grant', amount: 1000, status: 'estimated' },
    ],
  },
  {
    id: 'synthetic-student-006',
    bannerId: 'SYN000006',
    firstName: 'Student',
    lastName: 'Six',
    ssnLast4: '0000',
    ssnMasked: '***-**-0000',
    dob: '2000-01-01',
    email: 'student.six@example.com',
    phoneMasked: '(***) ***-0100',
    enrollmentStatus: 'admitted',
    program: 'Example Program',
    preferredLanguage: 'es',
    faDdxPopulated: false,
    awards: [{ kind: 'pell', amount: 1000, status: 'estimated' }],
  },
  {
    id: 'synthetic-student-007',
    bannerId: 'SYN000007',
    firstName: 'Student',
    lastName: 'Seven',
    ssnLast4: '0000',
    ssnMasked: '***-**-0000',
    dob: '2000-01-01',
    email: 'student.seven@example.com',
    phoneMasked: '(***) ***-0100',
    enrollmentStatus: 'enrolled',
    program: 'Example Program',
    preferredLanguage: 'en',
    faDdxPopulated: false,
    awards: [{ kind: 'pell', amount: 1000, status: 'estimated' }],
  },
  {
    id: 'synthetic-student-008',
    bannerId: 'SYN000008',
    firstName: 'Student',
    lastName: 'Eight',
    preferredName: 'Student',
    ssnLast4: '0000',
    ssnMasked: '***-**-0000',
    dob: '2000-01-01',
    email: 'student.eight@example.com',
    phoneMasked: '(***) ***-0100',
    enrollmentStatus: 'enrolled',
    program: 'Example Program',
    preferredLanguage: 'en',
    faDdxPopulated: true,
    awards: [
      { kind: 'pell', amount: 1000, status: 'estimated' },
      { kind: 'tops', amount: 1000, status: 'estimated' },
    ],
  },
  {
    id: 'synthetic-student-009',
    bannerId: 'SYN000009',
    firstName: 'Student',
    lastName: 'Nine',
    ssnLast4: '0000',
    ssnMasked: '***-**-0000',
    dob: '2000-01-01',
    email: 'student.nine@example.com',
    phoneMasked: '(***) ***-0100',
    enrollmentStatus: 'enrolled',
    program: 'Example Program',
    preferredLanguage: 'es',
    faDdxPopulated: true,
    awards: [
      { kind: 'pell', amount: 1000, status: 'awarded' },
      { kind: 'go_grant', amount: 1000, status: 'awarded' },
    ],
  },
  {
    id: 'synthetic-student-010',
    bannerId: 'SYN000010',
    firstName: 'Student',
    lastName: 'Ten',
    ssnLast4: '0000',
    ssnMasked: '***-**-0000',
    dob: '2000-01-01',
    email: 'student.ten@example.com',
    phoneMasked: '(***) ***-0100',
    enrollmentStatus: 'enrolled',
    program: 'Example Program',
    preferredLanguage: 'en',
    faDdxPopulated: false,
    awards: [{ kind: 'pell', amount: 1000, status: 'estimated' }],
  },
  {
    id: 'synthetic-student-011',
    bannerId: 'SYN000011',
    firstName: 'Student',
    lastName: 'Eleven',
    ssnLast4: '0000',
    ssnMasked: '***-**-0000',
    dob: '2000-01-01',
    email: 'student.eleven@example.com',
    phoneMasked: '(***) ***-0100',
    enrollmentStatus: 'enrolled',
    program: 'Example Program',
    preferredLanguage: 'en',
    faDdxPopulated: true,
    awards: [
      { kind: 'pell', amount: 1000, status: 'disbursed' },
      { kind: 'tops', amount: 1000, status: 'disbursed' },
    ],
  },
  {
    id: 'synthetic-student-012',
    bannerId: 'SYN000012',
    firstName: 'Student',
    lastName: 'Twelve',
    ssnLast4: '0000',
    ssnMasked: '***-**-0000',
    dob: '2000-01-01',
    email: 'student.twelve@example.com',
    phoneMasked: '(***) ***-0100',
    enrollmentStatus: 'enrolled',
    program: 'Example Program',
    preferredLanguage: 'en',
    faDdxPopulated: false,
    awards: [{ kind: 'pell', amount: 1000, status: 'estimated' }],
  },
]
